test = {   'name': 'q3',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> len(even_or_odd_list) == 20\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> even_or_odd_list[-1] == True\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> even_or_odd_list[0] == False\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> even_or_odd_dict[3] == False\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> even_or_odd_dict[4] == True\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
